name = "ucloud-push"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-14"

[build]
command = "worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "xxx"
database_id = "xxx-xxx"